sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - gh-pages # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
  - hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    all_branches: true 
    target_branch: gh-pages
  local-dir: public